---

kind: pipeline
type: docker
name: build pipeline

steps:

- name: unit tests
  image: golang:1.12-stretch
  pull: if-not-exists
  volumes:
  - name: go_cache
    path: /go
  commands:
    - cd app
    - go test -v

- name: go build
  image: golang:1.12-stretch
  pull: if-not-exists
  volumes:
  - name: go_cache
    path: /go
  commands:
  - cd app
  - go get
  - go build

- name: redis           
  image: redis:5.0-alpine
  detach: true

- name: smoke tests
  image: golang:1.12-stretch
  pull: if-not-exists
  commands:
    - apt-get update && apt-get install -y netcat
    - cd app
    - go get
    - go build -o test_run
    - ./test_run &
    - /bin/bash ../smoke.sh
  volumes:
  - name: go_cache
    path: /go
  environment:
    ERVCP_DB_HOST: redis
    ERVCP_DB_PORT: "6379"

- name: build & publish
  image: plugins/ecr
  privileged: true
  settings:
    repo:
      from_secret: repo
    registry: 
      from_secret: registry
    region: 
      from_secret: region
    tags:
      - ${DRONE_TARGET_BRANCH}
      - ${DRONE_COMMIT_SHA:0:8}
      - latest

volumes:
- name: go_cache
  host:
    path: /tmp/drone/cache/go

trigger:
  branch:
  - master
  event:
  - push
