---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    component: redis-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      component: rredis-replica
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: redis-replica
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: level
                operator: In
                values:
                - master
                - agent
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - redis-replica
              topologyKey: level
            weight: 50
      containers:
      - name: redis-replica
        image: redis-replica
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis-replica
          protocol: TCP
        command:
          - "redis-server"
        args:
          - "--slaveof"
          - "redis-master"
          - "6379"
        resources:
          limits:
            cpu: "0.1"
            memory: 50Mi 
