---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patches/resources.yaml
  - patches/service.yaml
  - patches/ports.yaml
  - patches/volume.yaml

namespace: default

images:
  - name: redis:5.0-alpine

replicas:
  - name: redis-master
    count: 1
    
commonLabels:
  environment: internal
  team: ervcp
  component: redis-master
