---
# tasks file for common

- name: update all
  yum:
    state: latest
    name: '*'

- name: install requirements
  yum:
    name: 
      - "{{ epel_release_rpm }}"
      - python-pip
    state: latest

- name: install ansible requirements
  pip:
    name: 
      - docker
      - boto3
