---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - role-binding.yaml
  - role.yaml
  - cronjob.yaml

configMapGenerator:
  - name: cron-update
    files:
      - scripts/image_check.sh
    behavior: create
