---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cron-update
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "pods"]
    verbs: ["get","list","patch","update"]
