---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    component: redis-replica
spec:
  template:
    spec:
      containers:
        - name: redis-replica
          ports:
            - containerPort: 6379
              $patch: delete
            - containerPort: 6379
              protocol: TCP
              name: redis-replica
