---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    component: redis-replica
spec:
  template:
    spec:
      containers:
        - name: redis-replica
          resources:
            limits:
              cpu: "0.1"
              memory: 50Mi 
