---

apiVersion: v1
kind: Service
metadata:
  name: redis-replica
spec:
  selector:
    component: redis-replica
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis-replica
