---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ervcp
  labels:
    component: ervcp
spec:
  template:
    spec:
      containers:
        - name: ervcp
      imagePullSecrets:
        - name: ecr-login-token
